name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Build binaries
        run: |
          mkdir -p cmd/webpanel
          cp main.go cmd/webpanel/
          mkdir -p internal/module internal/site internal/php internal/proxy internal/backup internal/database internal/utils pkg/caddy
          
          # Create empty files to ensure directories are built properly
          touch internal/module/.gitkeep internal/site/.gitkeep internal/php/.gitkeep 
          touch internal/proxy/.gitkeep internal/backup/.gitkeep internal/database/.gitkeep 
          touch internal/utils/.gitkeep pkg/caddy/.gitkeep
          
          # Make sure the module path is correct in all go files
          find . -name "*.go" -type f -exec sed -i 's|github.com/yourusername/webpanel|github.com/doko89/webpanel|g' {} \;
          
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/webpanel_linux_amd64 ./cmd/webpanel
          GOOS=linux GOARCH=386 go build -o dist/webpanel_linux_i386 ./cmd/webpanel
          GOOS=linux GOARCH=arm64 go build -o dist/webpanel_linux_arm64 ./cmd/webpanel
          GOOS=linux GOARCH=arm GOARM=7 go build -o dist/webpanel_linux_armv7 ./cmd/webpanel
          GOOS=linux GOARCH=arm GOARM=6 go build -o dist/webpanel_linux_armv6 ./cmd/webpanel
          
          cd dist
          tar -czf webpanel_linux_amd64.tar.gz webpanel_linux_amd64
          tar -czf webpanel_linux_i386.tar.gz webpanel_linux_i386
          tar -czf webpanel_linux_arm64.tar.gz webpanel_linux_arm64
          tar -czf webpanel_linux_armv7.tar.gz webpanel_linux_armv7
          tar -czf webpanel_linux_armv6.tar.gz webpanel_linux_armv6

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/webpanel_linux_amd64.tar.gz
            dist/webpanel_linux_i386.tar.gz
            dist/webpanel_linux_arm64.tar.gz
            dist/webpanel_linux_armv7.tar.gz
            dist/webpanel_linux_armv6.tar.gz